#!/bin/sh
set -eu

prompt='NetKeep-E2E#'

printf '\r\n%s ' "$prompt"

while IFS= read -r command; do
    command="$(printf '%s' "$command" | tr -d '\r')"

    case "$command" in
        'terminal length 0'|'terminal width 0')
            ;;
        'show version')
            printf '%s\r\n' \
                'Cisco IOS Software, C800 Software (C800-UNIVERSALK9-M), Version 15.8(3)M9' \
                'Compiled Mon 01-Jun-26 00:00 by NetKeep' \
                'NETKEEP-E2E processor with 262144K bytes of memory.' \
                'Processor board ID NETKEEP0001'
            ;;
        'show vtp status')
            printf '%s\r\n' \
                'VTP Version capable             : 1 to 3' \
                'VTP version running             : 2' \
                'VTP Operating Mode              : Transparent'
            ;;
        'show inventory')
            printf '%s\r\n' \
                'NAME: "NetKeep E2E", DESCR: "Virtual network device"' \
                'PID: NETKEEP-E2E, VID: V01, SN: NETKEEP0001'
            ;;
        'show running-config')
            printf '%s\r\n' \
                'Building configuration...' \
                '' \
                'Current configuration : 384 bytes' \
                '!' \
                'version 15.8' \
                'service timestamps log datetime msec' \
                'hostname NETKEEP-E2E' \
                '!' \
                'interface GigabitEthernet0/0' \
                ' description NetKeep E2E simulated uplink' \
                ' ip address 192.0.2.10 255.255.255.0' \
                ' no shutdown' \
                '!' \
                'line vty 0 4' \
                ' transport input ssh' \
                '!' \
                'end'
            ;;
        'exit'|'logout')
            exit 0
            ;;
        '')
            ;;
        *)
            printf '%% Invalid input detected at '\''^'\'' marker.\r\n'
            ;;
    esac

    printf '%s ' "$prompt"
done
