# syntax=docker/dockerfile:1.7@sha256:a57df69d0ea827fb7266491f2813635de6f17269be881f696fbfdf2d83dda33e

FROM oxidized/oxidized:0.37.0@sha256:07d8d7d669bb210b1100d121bbe214a3d64d621b1768f8f2179a1508a772541e

USER root

RUN apt-get update \
    && apt-get upgrade -y --no-install-recommends \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /etc/service \
    && ln -s /home/oxidized/.config/oxidized/.ssh /home/oxidized/.ssh \
    && chown -h 30000:30000 /home/oxidized/.ssh

LABEL org.opencontainers.image.title="NetKeep Oxidized" \
    org.opencontainers.image.authors="Lucas Quaresma <keep@lrq.lat>" \
    org.opencontainers.image.source="https://github.com/lrqnet/NetKeep" \
    org.opencontainers.image.licenses="Apache-2.0"

USER 30000:30000

ENTRYPOINT ["/usr/bin/dumb-init", "--"]
CMD ["oxidized"]
