<?php

return [
    'version' => '0.37.0',
    'models' => [
        'acmepacket', 'acos', 'acsw', 'addpack', 'adtran', 'adva', 'aen',
        'aireos', 'airfiber', 'airos', 'alteonos', 'alvarion', 'aos', 'aos7',
        'aoscx', 'aosw', 'apc_aos', 'apcaos', 'arbos', 'aricentiss',
        'arubainstant', 'asa', 'asternos', 'asyncos', 'audiocodes',
        'audiocodesmp', 'awplus', 'axos', 'bdcom', 'boss', 'br6910', 'c4cmts',
        'cambium', 'cambiumepmp', 'casa', 'catos', 'ciscoce', 'cisconga',
        'ciscosma', 'ciscosmb', 'ciscovpn3k', 'cnos', 'comnetms', 'comtrol',
        'comware', 'coriant8600', 'coriantgroove', 'corianttmos', 'cumulus',
        'datacom', 'dcnos', 'defacto', 'dellx', 'dlink', 'dlinknextgen', 'dnos',
        'dslcommands', 'dslsetup', 'eatonnetwork', 'eciapollo', 'edgecos',
        'edgeos', 'edgeswitch', 'efos', 'eltex', 'enterasys', 'enterasys800',
        'enterprise_sonic', 'eos', 'exalink', 'f5os', 'fabricos', 'fastiron',
        'fiberdriver', 'firebrick', 'firelinuxos', 'firewareos', 'fortigate',
        'fortios', 'fortiwlc', 'fsos', 'ftos', 'fujitsupy', 'gaiaos',
        'garderos', 'gcombnps', 'grandstream', 'grandstreamht8xx', 'h3c',
        'hatteras', 'hios', 'hirschmann', 'hpebladesystem', 'hpemsa', 'hpmsm',
        'ibos', 'icotera', 'ingate', 'ios', 'iosxe', 'iosxr', 'ipos',
        'ironware', 'isam', 'ivanti', 'junos', 'kornfeldos', 'lancom',
        'lenovonos', 'linksyssrw', 'linuxgeneric', 'macros', 'masteros',
        'mimosab11', 'ml66', 'mlnxos', 'model', 'mtrlrfs', 'ndms', 'necix',
        'netgear', 'netonix', 'netscaler', 'nodegrid', 'nos', 'nsxconfig',
        'nsxdfw', 'nsxfirewall', 'nxos', 'ocnos', 'onefinity', 'oneos',
        'openbsd', 'opengear', 'openwrt', 'opnsense', 'os10', 'os6', 'outputs',
        'panos', 'panos_api', 'perle', 'pfsense', 'planet', 'powerconnect',
        'procurve', 'purityos', 'qtech', 'quantaos', 'raisecom', 'rgos',
        'riverbed', 'routeros', 'saos', 'saos10', 'screenos', 'sgos', 'siklu',
        'siklumhtg', 'sixwind', 'slxos', 'smartax', 'smartbyte', 'smartcs',
        'sonicos', 'speedtouch', 'sros', 'srosmd', 'stoneos', 'supermicro',
        'swos', 'tdre', 'telco', 'tmos', 'tnsr', 'tplink', 'trango', 'truenas',
        'ucs', 'unifiap', 'uplinkolt', 'viptela', 'voltaire', 'voss', 'vrp',
        'vyatta', 'vyos', 'weos', 'xos', 'yamaha', 'zhoneolt', 'zteolt',
        'zy1308', 'zynos', 'zynosadsl', 'zynoscli', 'zynosgs', 'zynosmgs',
    ],
];
