<?php

return [
    'reviewed_drivers' => [
        'comware',
        'dnos',
        'edgeos',
        'eos',
        'fortios',
        'ios',
        'iosxe',
        'iosxr',
        'junos',
        'nxos',
        'procurve',
        'routeros',
        'vrp',
        'vyos',
    ],
    'safe_commands' => [
        'comware' => ['display current-configuration'],
        'dnos' => ['show running-config'],
        'edgeos' => ['show configuration commands'],
        'eos' => ['show running-config'],
        'fortios' => ['show full-configuration'],
        'ios' => ['show running-config'],
        'iosxe' => ['show running-config'],
        'iosxr' => ['show running-config'],
        'junos' => ['show configuration | display set'],
        'nxos' => ['show running-config'],
        'procurve' => ['show running-config'],
        'routeros' => ['/export show-sensitive'],
        'vrp' => ['display current-configuration'],
        'vyos' => ['show configuration commands'],
    ],
    'session_commands' => [
        '',
        'terminal length 0',
        'terminal width 0',
        'screen-length 0 temporary',
        'set cli screen-length 0',
        'set cli screen-width 0',
    ],
    'logout_commands' => ['', 'exit', 'logout', 'quit'],
];
